version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: seattle_flu
  # placeholder for building worker
  workers:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: idm-docker-production.packages.idmod.org/sfim-worker:${version:-latest}
    command: touch t
  service:
      build:
        context: api_service
        dockerfile: Dockerfile
      image: idm-docker-production.packages.idmod.org/sfim-api:${version:-latest}
      volumes:
       - db-data:/var/lib/mysql/data
      volumes:
        - /model_store:/model_store
        # pass docker so we can execute other containers
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        - SQLALCHEMY_URI=postgres+psycopg2://seattle_flu:@db
        - "CREATE_DB=1"
        #- "MODEL_HOST_PATH=`pwd`/test_model_store"
        #- "DEBUG_TOKENS=1"
      depends_on:
      - db
      ports:
       - "80:80"