version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: seattle_flu
      POSTGRES_PASSWORD: seattle_flu
      
  service:
    build:
      context: .
      dockerfile: Dockerfile
    image: idm-docker-production.packages.idmod.org/sfim
    ports:
      - 5000:80
    volumes:
      - "./test_model_store:/model_store"
    environment:
    - "CREATE_DB=1"
    - "SQLALCHEMY_URI=postgres+psycopg2://seattle_flu:@db"



